# Generated by Django 3.0.7 on 2020-06-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200616_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='porfile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
