# Generated by Django 3.0.7 on 2020-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_porfile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='customer',
            name='porfile_pic',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
